sudo: false
language: python
services:
  - postgresql
python:
  - 3.6
env:
  global:
    - URSH_CONFIG=/dev/null
install:
  - pip install flake8
  - pip install isort
  - pip install -e .
script:
  - flake8 .
  - isort --check-only --diff --quiet

notifications:
  email: false
