sudo: false
language: python
addons:
  postgresql: 9.6
python:
  - 3.6
env:
  global:
    - URSH_CONFIG=/dev/null
install:
  - pip install flake8
  - pip install isort
  - pip install -e .
script:
  - flake8 .
  - isort --check-only --diff --quiet
  - pytest
notifications:
  email: false
